string = "JDPWDJGLOFYBDQALKYFDPPFTYOFKQYICSHDQMIDKKYOESRQBYOFOKRJDHYRBYPYKOYXTLSQRBYILCDIQRDRFLKRBFKHQBYJDWBDTYEYYKHFOKDMMYOESRRBYPYBDQEYYKKLPDKQLJOYJDKODKORBYPYFQKLRBFKAJSCBRLALLKBYPPLLJBDOEYYKPDKQDCHYODKOQBYIYZRKLJYQQDAYESRQLJYRBFKARYIIQJYQBYFQLHDKOUYQBLSIOJLTYLKFRBFKHQBYJDWBDTYMIDKKYORBFQJYDKUBFIYFBDTYRBYOLCSJYKRGLOFYUDKRYOZPLJILKOLKFOLKRHKLUBLUQBYHKYUESRRBYZFZRBCBDMRYPUDQBFOOYKFKDCDTFRWFKDQRLKYIFKRYIFKQLJYPYJDFKQFKRBYYMBYQSQPLLJDRRBYEPFRFQBJSQYSJFRUDQYKCPWMRYOSQFKADKLRBYPMLIWDIMBDEYRFCCFMBYPFKTYKRYOFKRBYKFKYRYYKRBCYKRSPWFDQHYORBYJSQYSJRLRYQRFRDKORBYOLCSJYKRFQDSRBYKRFCQLFASYQQRBYFJMYPFDICFMBYPQCBLLIPYDIIWBDOJLTYOLKMYPBDMQFQBLSIOKRBDTYEYYKQSPMPFQYODZRYPRBYOFQCLTYPWDRELOPSJESRFRIYDTYQJYULKOYPFKAUBDRYIQYRBYWOYTYILMYOLKYLOOZYDRSPYUDQDZPFYXYPSKKFKAPLSKORBPYYQFOYQLZRBYIFKRYICLKQFQRFKALZDQFKAIYPLULZEIDCHDKOUBFRYRFIYQRBDRRBYJSQYSJRBFKHUYPYDOOYOFKRBYPLJDKMYPFLORBYWPYDOFKQYNSYKCYUUEEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEEUUUEUUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUUEUUUEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUEUUUEUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUEUUUEUUUUEUUUEEEUUUUUEEEUUUEUUUEUUUEUUUEUUUUEEEUUEUUUEUEEEUUUEEEEUUEEEUUUEEEUUEEEUEUUUEUUUUEUEUUEUUEUUUEUUUUUEUEUUEEUUEUUEUEUUUUEUUUEEUEEUEUUEUUEUUUUUEUUEUUUEUUUUEUUUEUUUEUUEUUUEUEUUUEUEUUUUUEUUUEUEUEUEUEUUUEUUUEUUUEUEUEUEUUEUUEUUUUUEUUUEUUEUUUUEUUEUUUEUUUEEEEEUEEEEUUEUUUUUEEEEEUEUEUEUEEEEEUUUEUUUEUUUEUEEEEUUEEEUUUEEEEUUUEUUUUEUUUEUUUEUUEUUUEUEUEUUUEUUUUUEUUUEUEUEUEUEUUUEUUUEUUUEUUUEUEUUUUUEUUUUUEUEUUUUEUUUUEUUEUUUEUUUEUUUEUEUUEUUUEUUUUEUUUEUEUUEEUEUUUEUUUEUUUEUUUEUEUUUUUEUUUUUEUUEUUUEUUUUEUUUEUUUEUUEUUUEUEUUUEUUUEEEUEUUUEUEUUUEUEUUUEUUEEEUUEUUUEUEUUUUUEEEEUUEUUUEUEEEUUEEEUEUUUEUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUEUUUEUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUEUUUEUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUEUUUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUUUEUUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUEEEUUEUUUEUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUUEUUEUUFBDTYSQYOEZLPRBYEIDCHRFIYQDKOUZLPRBYUBFRYLKYQFRRLLHJYDUBFIYRLZFASPYLSRRBDRRBYZPFYXYFQQRYADKLAPDMBWCLKCYDIFKARBYHYWULPOZLPRBYCFMBYPFKCBDMRYPZFTYUFRBLSRGLOFYFDJKLRQSPYUBYPYRLALKYVRRBYPYDPYLKIWRULMLQQFEFIFRFYQDQZDPDQFCDKQYYESRFBDTYKLFOYDUBYPYLKYLZRBYJFQDKODQZDPDQFCDKRYIIKLLKYYIQYHKLUQYFRBYPQLFASYQQFUFIIBYDOZLPLIWJMFDQYYWLSRBYPY"
ASCII = [[0, chr(i)] for i in range(0,255)]
for letter in string:
    if letter != ' ':
        ASCII[ord(letter)][0] += 1
ASCII.sort()
ASCII.reverse()
print(ASCII)
slownik = {
    "Y" : "E" ,
    "R" : "T" ,
    "K" : "N" ,
    "F" : "I" ,
    "D" : "A" ,
    "L" : "O" ,
    "B" : "H" ,
    "Q" : "S" ,
    "P" : "R" ,
    "O" : "D" ,
    "I" : "L" ,
    "S" : "U" ,
    "J" : "M" ,
    "C" : "C" ,
    "U" : "W" ,
    "M" : "P" ,
    "Z" : "F" ,
    "E" : "B" ,
    "A" : "G" ,
    "W" : "Y" ,
    "T" : "V" ,
    "H" : "K" ,
    "X" : "X" ,
    "G" : "J" ,
    "V" : "Z" ,
    "N" : "Q"
}
newstring = ""
for letter in string:
    newstring += slownik[letter]
print(newstring)